routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('homepage');
// });

Route::get('/profile', 'ProfileController@show')->name('profile.show');
Route::get('/profile/destroy', 'ProfileController@destroy')->name('profile.delete');
Route::post('/profile', 'ProfileController@store')->name('profile.store');

Auth::routes();

Route::get('/', 'HomeController@index')->name('homepage');
Route::get('/joboffers', 'JobOfferController@index')->name('joboffer');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::post('/contact', 'HomeController@sendMail')->name('sendMail');
Route::get('/about-us', 'HomeController@company')->name('company');
Route::get('joboffer/details', 'JobOfferController@show')->name('details');
Route::get('/jobapplication/{id}', 'JobApplicationController@store');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('../storage/app/images/{path}', 'MediaController@show')->name('media');


Route::middleware('admin')->prefix('/admin')->group(function () {
    Route::get('/', 'AdminController@show')->name('admin');
    Route::get('/joboffers', 'AdminController@indexJobOffers')->name('admin.indexJobOffers');
    Route::get('/joboffer/{id}', 'AdminController@showJobOffer')->name('admin.showJobOffer');
    Route::delete('/joboffer/{id}', 'AdminController@destroyJobOffer')->name('admin.destroyJobOffer');
    Route::get('/clients', 'AdminController@showClients')->name('admin.clients');
    Route::delete('/clients/{id}', 'AdminController@destroyClient')->name('admin.destroyClient');
    Route::delete('/jobapplications{id}', 'AdminController@destroyJobApplication')->name('admin.destroyJobApplication');
    Route::get('/profile', 'AdminController@showProfile')->name('admin.profile');
});

Route::resource('client', 'ClientController');
Route::resource('joboffer', 'JobOfferController');

resources/views/company.blade.php
@extends('layouts.layout')

@section('content')
    <!-- Page Content-->

    <section class="section-padding light-gray-bg">
        <div class="container">
            <div class="text-center mb-80">
                <h2 class="section-title text-uppercase">About us</h2>
                <p class="section-sub">Luxury Services is a leading professional recruitment consultancy specialising in the recruitment of permanent, contract and temporary positions on behalf of the world’s top employers.</p>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="featured-item feature-icon icon-hover icon-hover-brand icon-circle icon-outline clearfix">
                        <div class="icon">
                            <i class="material-icons">&#xE8E8;</i>
                        </div>
                        <div class="desc">
                            <h3 class="text-extrabold">Verified jobs</h3>
                            <p>Checked and sorted, our job offers are updated regularly to offer you the best opportunities in the industry.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="featured-item feature-icon icon-hover icon-hover-brand icon-circle icon-outline clearfix">
                        <div class="icon">
                            <i class="material-icons">&#xE84E;</i>
                        </div>
                        <div class="desc">
                            <h3 class="text-extrabold">Recruitment</h3>
                            <p>Precise and personalized, we make sure they don’t skip a step: verifying tickets, diplomas and consulting references.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="featured-item feature-icon icon-hover icon-hover-brand icon-circle icon-outline clearfix">
                        <div class="icon">
                            <i class="material-icons">&#xE903;</i>
                        </div>
                        <div class="desc">
                            <h3 class="text-extrabold">Experienced</h3>
                            <p>We know the importance of efficiency and availability. These qualities are therefore our watchwords.</p>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="promo-box promo-parallax mt-80 mb-80 ptb-70 text-center">
                        <div class="promo-info">
                            <h1 class="text-uppercase mb-30 text-extrabold font-30">We provide customized services on demand</h1>
                            <p class="width-60 mb-30">You know that attracting and retaining top talent is vital for the success of your business. It’s that end result you’re focused on – hiring a great team – and not the process to get there. This is where we can help...</p>

                            <a href="{{ route('contact') }}" class="btn btn-lg border secondary waves-effect waves-light mt-20"><span><strong>Get in touch</strong> with us</span></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <p class="text-center mb-80">The role of a recruitment consultancy is to act as an intermediary, identifying and sourcing suitably qualified candidates on behalf of its clients. Candidates are recruited either for permanent or contract positions (typically for a fixed term) or on a temporary basis. Within the overall recruitment industry, the market for professional recruitment services is a specialist sector which has developed more recently.</p>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div id="project-slider" class="carousel slide boot-slider" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#project-slider" data-slide-to="0" class="active"></li>
                            <li data-target="#project-slider" data-slide-to="1"></li>
                        </ol>

                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img class="img-responsive" src="../assets/img/slide1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive" src="../assets/img/slide2.jpg" alt="">
                            </div>
                        </div>

                        <a class="left carousel-control" href="#project-slider" role="button" data-slide="prev">
                            <span class="fa fa-angle-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#project-slider" role="button" data-slide="next">
                            <span class="fa fa-angle-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <h3 class="no-margin text-extrabold">Our philosophy</h3>
                    <p class="mt-20 mb-20">
                        Luxury Services is one of the world's leading professional recruitment consultancies, specializing in the placement of candidates in permanent, contract, temporary and interim positions with clients around the world.
                        <br>The Group has established a leading presence in many of the key markets for professional recruitment around the world and has positioned itself in certain other markets, which offer the opportunity for future growth.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="padding-top-110 padding-bottom-70 brand-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="quote-carousel text-center">

                        <div class="carousel-item">
                            <div class="content">
                                <h2 class="white-text line-height-40">"Get in touch with Luxury Services to leave the port for the season with the
                                    right crew, and a peace of mind knowing that whatever situation arises we will
                                    be there to help."</h2>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="content">
                                <h2 class="white-text line-height-40">"My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time."</h2>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="content">
                                <h2 class="white-text line-height-40">"My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time."</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/contact.blade.php
@extends('layouts.layout')

@section('content')
    <!-- Page Content-->
    <form method="POST" action="{{ route('sendMail') }}" accept-charset="UTF-8" id="formContact" class="light-gray-bg">
    @csrf
        <input name="_token" type="hidden" value="{{ csrf_token() }}">
        <input name="job_id" type="hidden" value="">
        <section class="section-padding">
            <div class="container">
                <div class="text-center mb-80">
                    <h2 class="section-title text-uppercase">Drop us a line</h2>
                    <p class="section-sub text-center">Whether your needs, desires or wishes are urgent or a little less, they will all be taken care of with the some efficiency by us.</p>
                </div>

                <div class="row">
                    <div id="contactForm" class="col-xs-12 col-sm-12 col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-field">
                                    <input required="required" name="firstname" type="text">
                                    <label for="firstname">First name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="input-field">
                                    <input required="required" name="lastname" type="text">
                                    <label for="lastname">Last name</label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-field">
                                    <input required="required" name="email" type="email">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="input-field">
                                    <input required="required" name="phone" type="tel">
                                    <label for="phone">Phone Number</label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-field">
                                    <textarea class="materialize-textarea" required="required" name="message" cols="50" rows="10"></textarea>
                                    <label for="message">Message</label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <button type="submit"
                                        name="submit"
                                        class="btn btn-block gradient primary waves-effect waves-light submit-button">
                                    Send Message
                                </button>
                                @if(Session::has('flash_message'))
                                    <div class="black-text btn btn-block btn-success mt-30 waves-effect waves-dark disabled">{{ Session::get('flash_message') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 contact-info mt-40">

                        <address>
                            <i class="material-icons brand-color">&#xE55F;</i>
                            <div class="address">
                                <p>Luxury Services is based in Roanne, on Loire department</p>
                            </div>
                            <i class="material-icons brand-color">&#xE61C;</i>
                            <div class="phone">
                                <p>+33 (0) 6 60 06 66 00</p>
                            </div>
                            <i class="material-icons brand-color">&#xE916;</i>
                            <div class="phone">
                                <p>9 - 22h with 24/7 speaker</p>
                            </div>
                            <i class="material-icons brand-color">&#xE0E1;</i>
                            <div class="mail">
                                <p><a href="#!">georges[a]luxuryservices.com</a></p>
                            </div>
                        </address>
                    </div>
                </div>
            </div>
        </section>
    </form>
    <div id="myMap" class="height-350">Gmap here</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/homepage.blade.php
@extends('layouts.layout')

    @if(session('error'))
        <div class="btn btn-block btn-failed mt-30 waves-effect waves-light disabled">{{ session('error') }}</div>
    @elseif(session('confirmation'))
        <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">{{ session('confirmation') }}</div>
    @endif

    @section('content')

    @include('partials/slider')
    
        <!-- Page Content-->
        <!--<section class="full-width promo-box brand-bg ptb-50">-->
            <!--<div class="container">-->
                <!---->
            <!--</div>-->
        <!--</section>-->
        <section class="ptb-50 brand-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 mb-40">
                        <div class="promo-info">
                            <span class="white-text">Whether you're an employer or a candidate looking for jobs</span>
                            <h3 class="white-text text-bold text-uppercase no-margin">WE HAVE THE SOLUTION FOR YOU</h3>
                        </div>
                        <div class="promo-btn">
                            <a href="{{ route('contact') }}" class="btn border secondary waves-effect waves-light">Contact Us</a>
                        </div>
                    </div>
                </div>

                <hr class="mt-10 mb-50">

                <div class="text-center">
                    <h2 class="section-title primary-text">Who We are</h2>
                    <p class="section-sub white-text">Luxury Services is a leading professional recruitment consultancy specialising in the recruitment of permanent, contract and temporary positions on behalf of the world’s top employers.</p>
                </div>
                <br>

                <div class="row">
                    <div class="col-sm-6">
                        <div id="project-slider" class="carousel slide boot-slider" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#project-slider" data-slide-to="0" class="active"></li>
                                <li data-target="#project-slider" data-slide-to="1"></li>
                            </ol>

                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img class="img-responsive" src="assets/img/slide1.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="img-responsive" src="assets/img/slide2.jpg" alt="">
                                </div>
                            </div>

                            <a class="left carousel-control" href="#project-slider" role="button" data-slide="prev">
                                <span class="fa fa-angle-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#project-slider" role="button" data-slide="next">
                                <span class="fa fa-angle-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <h3 class="primary-text">Our philosophy</h3>
                        <p class="white-text">Our role is to work with employers and job seekers to facilitate a successful match. This can range from advising a global company on a candidate sourcing strategy to helping a job seeker find their dream job.</p>
                    </div>

                    <div class="text-center">
                        <a href="{{ route('company') }}" class="btn gradient secondary waves-effect waves-light mt-40">More about us</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
            <div class="container">
                <div class="row">
                    <div class="valign-wrapper text-center">
                        <div class="hero-intro valign-cell">
                            <h2 class="tt-headline clip is-full-width no-margin">
                                <span>You are </span>
                                <span class="tt-words-wrapper">
                                    <b class="is-visible">Commercial</b>
                                    <b>Creative</b>
                                    <b>Marketing & PR</b>
                                    <b>Technology</b>
                                    <b>Fashion & luxury</b>
                                    <b>Retail sales</b>
                                </span>
                            </h2>
                            <h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
                            <p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

                            <a href="{{ route('register') }}" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="job-offers" class="section-padding gray-bg">
            <div class="container">
                <div class="text-center mb-40">
                    <h2 class="section-title">We have the perfect job for you</h2>
                    <p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
                </div>
                <div class="portfolio-container">
                    <ul class="portfolio-filter brand-filter text-center">
                        <li class="active waves-effect waves-light" data-group="all">All</li>
                        <li class=" waves-effect waves-light" data-group="Commercial">Commercial</li>
                        <li class=" waves-effect waves-light" data-group="Retail Sales">Retail Sales</li>
                        <li class=" waves-effect waves-light" data-group="Creative">Creative</li>
                        <li class=" waves-effect waves-light" data-group="Technology">Technology</li>
                        <li class=" waves-effect waves-light" data-group="Marketing & PR">Marketing & PR</li>
                        <li class=" waves-effect waves-light" data-group="Fashion & Luxury">Fashion & Luxury</li>
                        <li class=" waves-effect waves-light" data-group="Management & HR">Management & HR</li>
                    </ul>
                    @if(session('error'))
                        <div class="btn btn-block btn-failed mt-30 waves-effect waves-light disabled">{{ session('error') }}</div>
                    @elseif(session('confirmation'))
                        <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">{{ session('confirmation') }}</div>
                    @endif
                    <div class="portfolio portfolio-with-title col-2 gutter mt-30">
                    @forelse($jobsList as $jobs)
                        <div class="portfolio-item" data-groups='["all", "{{ $jobs->job_category }}"]'>
                            <div class="portfolio-wrapper">
                                <div class="card job-card">
                                    <div class="card-content">
                                        <span class="title">
                                            <span class="card-title">{{ $jobs->job_title }}</span>
                                            <span class="ref grey-text">Ref. {{ $jobs->id }}</span>
                                        </span>
                                        <div class="metas mb-20">
                                            <div class="meta">
                                                <i class="material-icons">&#xE53E;</i>{{ $jobs->salary }} &euro;
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE916;</i>{{ $jobs->closing_at }}
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE55F;</i>{{ $jobs->location }}
                                            </div>
                                        </div>
                                        <p class="truncate-text">{{ $jobs->description }}</p>
                                    </div>
                                    <div class="card-action">
                                        <a class="btn btn-md primary border waves-effect waves-dark" href="{{ route('joboffer.show', ['id' => $jobs->id]) }}">Details</a>
                                        @if (isset($totalRounded) && $totalRounded == 100)
                                            <a class="btn btn-md primary waves-effect waves-light" href="{{ url("jobapplication/".$jobs->id )}}">Apply</a>
                                        @else
                                            <a class="btn btn-md primary waves-effect waves-light" href="{{ route('profile.show') }}">Apply</a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    @empty
                        <p>No job offers available</p>
                    @endforelse
                        <div class="no-item"></div>
                    </div>
                    <div class="text-center">
                        <a href="{{ route('joboffer') }}" class="btn gradient secondary waves-effect waves-light mt-30">View all job offers</a>
                    </div>
                </div>
            </div>
        </section>
    @endsection

resources/views/mail.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
    </head>
    <body>
        <ul>
            <li><strong>First name :</strong>{{ $_POST['firstname'] }}</li>
            <li><strong>Last name :</strong>{{ $_POST['lastname'] }}</li>
            <li><strong>Email :</strong>{{ $_POST['email'] }}</li>
            <li><strong>Phone Number :</strong>{{ $_POST['phone'] }}</li>
            <li><strong>Message :</strong>{{ $_POST['message'] }}</li>
        </ul>
    </body>
</html>